# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20171109_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='count',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
