# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='count',
        ),
    ]
